@extends('layouts.app')

@section('title', 'Inspection Map View | PPMF Portal')
@section('page_title', 'Inspection Map View')

@section('content')
<div class="page-actions-ppmf"><div><h2>Inspection Map View</h2><p>Map-based monitoring of inspection activities across Punjab.</p></div><div class="d-flex gap-2"><button class="btn btn-outline-success">Export PDF</button><button class="btn btn-success">Print</button></div></div>
<div class="filter-card-ppmf mb-4"><div class="filter-title"><i class="bi bi-funnel"></i> Filters</div><div class="row g-3 align-items-end"><div class="col-md-2"><label class="form-label">Division</label><select class="form-select"><option>All Divisions</option></select></div><div class="col-md-2"><label class="form-label">District</label><select class="form-select"><option>All Districts</option></select></div><div class="col-md-2"><label class="form-label">Frequency</label><select class="form-select"><option>Weekly</option><option>Monthly</option></select></div><div class="col-md-2"><label class="form-label">Month</label><select class="form-select"><option>May</option></select></div><div class="col-md-2"><label class="form-label">Year</label><select class="form-select"><option>2026</option></select></div><div class="col-md-2 d-flex gap-2"><button class="btn btn-success flex-fill">Apply</button><button class="btn btn-outline-secondary">Reset</button></div></div></div>
<div class="row g-3 mb-4"><div class="col-md-3"><div class="stat-card-ppmf border-success"><span>Total</span><strong>36</strong><small>Districts</small></div></div><div class="col-md-3"><div class="stat-card-ppmf border-primary"><span>Reported</span><strong>29</strong><small>Submitted</small></div></div><div class="col-md-3"><div class="stat-card-ppmf border-warning"><span>Pending</span><strong>5</strong><small>Waiting</small></div></div><div class="col-md-3"><div class="stat-card-ppmf border-danger"><span>Flagged</span><strong>2</strong><small>Attention</small></div></div></div>
<div class="card-ppmf"><div class="card-ppmf-header"><div class="card-ppmf-title"><i class="bi bi-map"></i> Punjab Map Placeholder</div></div><div class="card-ppmf-body"><div class="map-placeholder-ppmf"><i class="bi bi-map-fill"></i><h5>Interactive Punjab Map</h5><p>Integrate Highmaps/SVG map here later.</p></div></div></div>
<div class="card-ppmf"><div class="card-ppmf-header"><div><div class="card-ppmf-title"><i class="bi bi-table"></i> Records</div><div class="card-ppmf-subtitle">Static sample data. Connect backend later.</div></div><div class="d-flex gap-2"><button class="btn btn-sm btn-outline-success">Export Excel</button><button class="btn btn-sm btn-success">Print</button></div></div><div class="card-ppmf-body"><div class="table-responsive"><table class="table table-ppmf align-middle"><thead><tr><th>#</th><th>District</th><th>Division</th><th>Total KPIs</th><th>Score</th><th>Status</th><th>Action</th></tr></thead><tbody><tr><td>1</td><td>Faisalabad</td><td>Faisalabad</td><td>42</td><td class="text-success fw-bold">88%</td><td><span class="badge bg-success-subtle text-success">On Track</span></td><td><button class="btn btn-sm btn-outline-success">View</button></td></tr><tr><td>2</td><td>Lahore</td><td>Lahore</td><td>40</td><td class="text-success fw-bold">85%</td><td><span class="badge bg-success-subtle text-success">Good</span></td><td><button class="btn btn-sm btn-outline-success">View</button></td></tr><tr><td>3</td><td>Multan</td><td>Multan</td><td>35</td><td class="text-warning fw-bold">69%</td><td><span class="badge bg-warning-subtle text-warning">Average</span></td><td><button class="btn btn-sm btn-outline-success">View</button></td></tr></tbody></table></div></div></div>
@endsection
