@extends('layouts.app')
@section('title','Submit '.$kpiCard->title.' KPI Data')
@push('styles')<link rel="stylesheet" href="{{ asset('css/ppmu-kpi.css') }}">@endpush
@section('content')
<div class="ppmu-page-head"><div><a class="ppmu-back" href="{{ route('kpi.dashboard',$kpiCard) }}"><i class="bi bi-arrow-left"></i> {{ $kpiCard->title }} Dashboard</a><div class="ppmu-eyebrow">Dynamic KPI Form</div><h1>Submit {{ $kpiCard->title }} Data</h1><p>{{ ucfirst($kpiCard->frequency) }} reporting form for your assigned location.</p></div></div>
<form method="POST" action="{{ route('kpi-submissions.store',$kpiCard) }}" class="card-ppmf">@csrf<div class="card-ppmf-body"><div class="row g-3">@if($errors->any())<div class="col-12"><div class="alert alert-danger">{{ $errors->first() }}</div></div>@endif
<div class="col-md-4"><label class="form-label">Period Type</label><select name="period_type" class="form-select" required>@foreach(['weekly','monthly','quarterly','yearly'] as $type)<option value="{{ $type }}" @selected(old('period_type',$kpiCard->frequency)===$type)>{{ ucfirst($type) }}</option>@endforeach</select></div><div class="col-md-4"><label class="form-label">Period Label</label><input name="period_label" class="form-control" required value="{{ old('period_label',now()->format('F Y')) }}"></div><div class="col-md-4"><label class="form-label">Submission Date</label><input type="date" name="submission_date" class="form-control" required value="{{ old('submission_date',now()->toDateString()) }}"></div>
@foreach($kpiCard->formFields as $field)<div class="{{ $field->field_type==='textarea' ? 'col-12' : 'col-md-6' }}"><label class="form-label">{{ $field->field_label }} @if($field->is_required)<span class="text-danger">*</span>@endif</label>@if($field->field_type==='textarea')<textarea name="fields[{{ $field->id }}]" class="form-control" rows="3" @required($field->is_required)>{{ old('fields.'.$field->id) }}</textarea>@elseif($field->field_type==='select')<select name="fields[{{ $field->id }}]" class="form-select" @required($field->is_required)>@foreach($field->options ?: [] as $option)<option>{{ $option }}</option>@endforeach</select>@else<input type="{{ in_array($field->field_type,['number','date']) ? $field->field_type : 'text' }}" name="fields[{{ $field->id }}]" value="{{ old('fields.'.$field->id) }}" class="form-control" @required($field->is_required)>@endif</div>@endforeach
<div class="col-12"><label class="form-label">Remarks</label><textarea name="remarks" class="form-control" rows="3">{{ old('remarks') }}</textarea></div><div class="col-12 d-flex justify-content-end gap-2"><a href="{{ route('kpi.dashboard',$kpiCard) }}" class="btn btn-outline-secondary">Cancel</a><button class="btn btn-success"><i class="bi bi-send me-2"></i>Submit KPI Data</button></div></div></div></form>@endsection
