@extends('layouts.app')
@section('title',$card->exists ? 'Edit KPI Card' : 'Create KPI Card')
@push('styles')<link rel="stylesheet" href="{{ asset('css/ppmu-kpi.css') }}">@endpush
@section('content')
<div class="ppmu-page-head"><div><a class="ppmu-back" href="{{ route('manage-kpis.index') }}"><i class="bi bi-arrow-left"></i> Manage KPIs</a><h1>{{ $card->exists ? 'Edit' : 'Create' }} KPI Card</h1><p>Configure the card identity, reporting cycle and display settings.</p></div></div>
<form method="POST" action="{{ $card->exists ? route('manage-kpis.update',$card) : route('manage-kpis.store') }}" class="card-ppmf">@csrf @if($card->exists)@method('PUT')@endif<div class="card-ppmf-body"><div class="row g-3">
@if($errors->any())<div class="col-12"><div class="alert alert-danger">{{ $errors->first() }}</div></div>@endif
<div class="col-md-6"><label class="form-label">KPI Title</label><input class="form-control" name="title" required value="{{ old('title',$card->title) }}"></div><div class="col-md-6"><label class="form-label">Slug</label><input class="form-control" name="slug" value="{{ old('slug',$card->slug) }}" placeholder="Generated from title if blank"></div>
<div class="col-md-4"><label class="form-label">Category</label><input class="form-control" name="category" required value="{{ old('category',$card->category) }}"></div><div class="col-md-4"><label class="form-label">Frequency</label><select class="form-select" name="frequency">@foreach(['daily','weekly','monthly','yearly'] as $item)<option value="{{ $item }}" @selected(old('frequency',$card->frequency)===$item)>{{ ucfirst($item) }}</option>@endforeach</select></div><div class="col-md-4"><label class="form-label">Fallback Icon</label><input class="form-control" name="icon" required value="{{ old('icon',$card->icon ?: 'bi-speedometer2') }}"></div>
<div class="col-md-8"><label class="form-label">KPI Image Path</label><input class="form-control" name="image_path" value="{{ old('image_path',$card->image_path) }}" placeholder="images/kpi-images/example.png"></div>
<div class="col-md-4"><label class="form-label">Total Marks</label><input class="form-control" type="number" name="total_marks" min="1" required value="{{ old('total_marks',$card->total_marks ?: 100) }}"></div><div class="col-md-4"><label class="form-label">Display Order</label><input class="form-control" type="number" name="display_order" min="0" required value="{{ old('display_order',$card->display_order ?: 0) }}"></div><div class="col-md-4"><label class="form-label">Status</label><select class="form-select" name="is_active"><option value="1" @selected(old('is_active',$card->is_active ?? true))>Active</option><option value="0" @selected(!old('is_active',$card->is_active ?? true))>Inactive</option></select></div>
<div class="col-12"><label class="form-label">Description</label><textarea class="form-control" rows="4" name="description">{{ old('description',$card->description) }}</textarea></div><div class="col-12 d-flex justify-content-end gap-2"><a class="btn btn-outline-secondary" href="{{ route('manage-kpis.index') }}">Cancel</a><button class="btn btn-success">Save KPI Card</button></div>
</div></div></form>
@if($card->exists)
<div class="card-ppmf mt-4"><div class="card-ppmf-header"><div><div class="card-ppmf-title">Dynamic Form Builder</div><small class="text-muted">Fields appear automatically on the KPI submission form.</small></div></div><div class="table-responsive"><table class="table-ppmf ppmu-table"><thead><tr><th>Order</th><th>Label</th><th>Field Name</th><th>Type</th><th>Required</th><th></th></tr></thead><tbody>@forelse($card->formFields as $field)<tr><td>{{ $field->sort_order }}</td><td><strong>{{ $field->field_label }}</strong></td><td>{{ $field->field_name }}</td><td>{{ ucfirst($field->field_type) }}</td><td>{{ $field->is_required ? 'Yes' : 'No' }}</td><td><form method="POST" action="{{ route('manage-kpis.fields.destroy',[$card,$field]) }}" onsubmit="return confirm('Remove this field?')">@csrf @method('DELETE')<button class="btn btn-sm btn-outline-danger">Remove</button></form></td></tr>@empty<tr><td colspan="6" class="text-center text-muted py-4">No fields configured.</td></tr>@endforelse</tbody></table></div><form method="POST" action="{{ route('manage-kpis.fields.store',$card) }}" class="card-ppmf-body border-top">@csrf<div class="row g-3"><div class="col-md-3"><label class="form-label">Field Label</label><input name="field_label" required class="form-control"></div><div class="col-md-2"><label class="form-label">Field Name</label><input name="field_name" required class="form-control" placeholder="snake_case"></div><div class="col-md-2"><label class="form-label">Type</label><select name="field_type" class="form-select">@foreach(['text','number','date','textarea','select','radio','checkbox'] as $type)<option value="{{ $type }}">{{ ucfirst($type) }}</option>@endforeach</select></div><div class="col-md-2"><label class="form-label">Options</label><input name="options_text" class="form-control" placeholder="Comma separated"></div><div class="col-md-1"><label class="form-label">Order</label><input type="number" min="0" name="sort_order" value="{{ $card->formFields->max('sort_order')+1 }}" class="form-control"></div><div class="col-md-1 d-flex align-items-end"><label class="form-check mb-2"><input type="checkbox" name="is_required" value="1" class="form-check-input"> Required</label></div><div class="col-md-1 d-flex align-items-end"><button class="btn btn-success">Add</button></div></div></form></div>
@endif
@endsection
